### ISSUE TITLE
cannot import name 'Session' from 'econuy'

### ISSUE THREAD

**Issue by fededemo** [rxavier/econuy#7]
despues de realizar el `pip install`, cuando voy a correr:

`from econuy import Session
sess = Session(location="/Users/fededeleon/econuy")
df = sess.get(dataset="cpi").dataset`

me aparece el warning:
_cannot import name 'Session' from 'econuy'_

cómo lo puedo solucionar?

Muchas gracias!!

**Comment by rxavier** [comment]
Perdón la demora, sinceramente no vi este issue.

Tenía el README desactualizado luego de corregir un error. Tenés que hacer

`from econuy.session import Session`

Disculpá la confusión. Próximamente va a volver una funcionalidad, pero la tuve que retirar porque me estaba generando un problema con la creación de documentación.
